exp_log_name: "samplesize" # optional but recommended
data: "toy_2d" 
experiments: ["ScaleSampleSizeSW", "ScaleSampleSizeC2ST", "ScaleSampleSizeMMD", "ScaleSampleSizeFID",]
n: 4000
d: 2

seed: 0
runs: 5