exp_log_name: "MMD_scale_gamma" # optional but recommended
data: ["toy_2d" , "random", "random"]

experiments: ["ScaleGammaMMD", "ScaleGammaMMD", "ScaleGammaMMD"]
dim_sizes: [10, 100]
sample_size: [10000]

n:  [10000, 10000, 10000] 
d: [2, 10, 100]
val_min: [0.1, 1, 1]
val_max: [5, 20, 50]
val_step: [10, 10, 10]
augmentation: ['gauss', 'one_dim_shift', 'one_dim_shift',]

seed: 0
runs: 5



value_sizes: [[0.1, 0.2, 0.5,  0.75, 0.9, 1.0, 1.25, 1.5, 2, 2.5, 3.0, 4.0, 5.0], 
[0.1,1,1.5,2,2.5,3,4,5,6,8,10,12,14,16,18,20], [1,3,5,6,7,8,9,10,12,15,20,25,30,35,40]]