exp_log_name: "MMD_bandwidth_experiment" # optional but recommended

# datasets to use
data: ["toy_2d" , "random", "random"]
augmentation: ['gauss', 'one_dim_shift', 'one_dim_shift',]

# number of samples and dimensions
n:  [5000,5000,5000] #[10000, 10000, 10000] #samples Note that for main figure 10k
d: [2, 10, 100]
dim_sizes: [10, 100]

# bandwidth scaling experiments 
experiments: ["ScaleGammaMMD", "ScaleGammaMMD", "ScaleGammaMMD"]

# bandwidth range for each dataset
value_sizes: [
  [0.1, 0.2, 0.5,  0.75, 0.9, 1.0, 1.25, 1.5, 2, 2.5, 3.0, 4.0, 5.0],
  [0.1,1,1.5,2,2.5,3,4,5,6,8,10,12,14,16,18,20],
  [1,3,5,6,7,8,9,10,12,15,20,25,30,35,40]
  ]
# instead of a custom range one can also specify ranges here 
val_min: [0.1, 1, 1]
val_max: [5, 20, 50]
val_step: [10, 10, 10]

# number of runs for errorbars
runs: 5

# seed for reproducibility
seed: 0