exp_log_name: "MMD_sample_size_dimensionality" # optional but recommended
data: ["toy_2d" , "random", "random"]

experiments: ["ScaleSampleSizeMMD", "ScaleSampleSizeMMD",
 "ScaleSampleSizeMMD"] 
experiments_dim: ["ScaleDimMMD", "ScaleDimMMD", "ScaleDimMMD"]
dim_sizes: [5, 10, 50, 100, 500, 1000]
sample_size: [50, 100, 200, 500, 1000, 2000, 3000, 4000]

n:  [10000, 10000, 10000] 
d: [2, 10, 1000]

# each dataset has its own bandwidth range 
mmd_bandwidth: [[0.5, 1, 2],[1, 3, 5],[5, 10, 40]]
augmentation: ['gauss', 'one_dim_shift', 'one_dim_shift',]

seed: 0
runs: 5
runs_dim: 1 # only one run for dimensionality experiments


