exp_log_name: "scaling_dims" # optional but recommended
data: ["multivariate_normal"]
experiments: ["ScaleDimSW", "ScaleDimC2ST", "ScaleDimMMD"]
n: [100] # 1k final
d: [100]
distort: ["shift_one", "shift_all", "increase_var"]
dim_sizes: [5, 10, 50, 100, 500, 1000]
mmd_bandwidth: [10., 10., 10.]

seed: 1404
runs: 5

