exp_log_name: "scaling_dims" # optional but recommended
data: ["multivariate_normal"]
experiments: ["ScaleDimSW", "ScaleDimC2ST", "ScaleDimMMD"]
n: [1000]
d: [100]
distort: ["shift_one", "shift_all"]
dim_sizes: [5, 10, 15, 20, 25, 30, 40, 60, 80, 100]
mmd_bandwidth: [10., 10.]

seed: 1404
runs: 5

