exp_log_name: "embeddings_samplesize" # optional but recommended
data: ["imagenet_real_embeddings"]
experiments: ["ScaleSampleSizeSW", "ScaleSampleSizeC2ST", "ScaleSampleSizeMMD", "ScaleSampleSizeFID",]
n: [10000]
d: [2048]
augmentation: ['imagenet_uncond_embeddings']

seed: 0
runs: 5
bandwidth: 64 