exp_log_name: "main_scaling_experiment" # optional but recommended

# datasets to use
data: ["toy_2d" , "random", "random"]
augmentation: ['gauss', 'one_dim_shift', 'one_dim_shift',]

# number of samples and dimensions
n:  [10000, 10000, 10000] #samples 
d: [2, 10, 1000] # dimensions

mmd_bandwidth: [1, 5, 10]

# sample size experiments
experiments: ["ScaleSampleSizeSW", "ScaleSampleSizeC2ST","ScaleSampleSizeMMD"]
sample_size: [50, 100, 200, 500, 1000, 2000, 3000, 4000]
runs: 5 # number of sample selection for errorbars

# dimensionality experiments
experiments_dim: ["ScaleDimSW", "ScaleDimC2ST", "ScaleDimMMD"]
dim_sizes: [5, 10, 50, 100, 500, 1000]
runs_dim: 5 # number of sample selection for errorbars

# seed for reproducibility
seed: 0


# for the reduced sample size experiments
#sample_size: [8, 10, 20, 50, 80]
#n:  [500, 500, 500] 
