name: 'Push plots to Overleaf'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout python project on Github
        uses: actions/checkout@v4
      - name: Checkout Overleaf project
        run: git clone ${{ secrets.OVERLEAF_GIT_CLONE_URL }} overleaf/
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/labproject/
          python3 -m pip install --upgrade pip
          pip install -e ".[docs]"
      - name: Run experiments and generate plots
        run: |
          cd ${{ github.workspace }}/labproject/
          python3 labproject/run.py
          cd ..
          cp -r labproject/plots/* overleaf/figures/
      - name: Commit and push changes to Overleaf
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Github Actions"
          author_email: ""
          cwd: 'overleaf/'
          add: 'figures/'
          message: "Update figures automatically"